FROM httpd:alpine

ARG JBROWSE_VERSION
ARG APOLLO_VERSION

WORKDIR /tmp
COPY scripts/configure_proxy.sh /tmp/
COPY scripts/setup_jbrowse.sh /tmp/

RUN chmod +x /tmp/configure_proxy.sh /tmp/setup_jbrowse.sh

RUN /tmp/configure_proxy.sh

WORKDIR /usr/local/apache2/htdocs/

RUN /tmp/setup_jbrowse.sh

RUN rm -rf /tmp/configure_proxy.sh /tmp/setup_jbrowse.sh