volumes:
  # Galaxy volumes
  galaxy-postgres-data: null
  galaxy-conda: null
  # Apollo volumes
  apollo-mongo-data: null
  apollo-mongo-config: null
  apollo-mongo-replica-data: null
  apollo-mongo-replica-config: null
  apollo-uploads: null

services:
  # ===== GALAXY SERVICES =====
  galaxy-app:
    build:
      context: ./containers/galaxy
      dockerfile: Dockerfile.app
    image: galaxy-app
    container_name: galaxy-app
    platform: linux/amd64
    ports:
      - "8080:80"
      - "9002:9002" # for logs
    env_file: ./.envs/.galaxy
    volumes:
      - ./logs:/home/galaxy/logs
      - ./galaxy-data:/export
      # - ../workshop:/galaxy/tools
      - ./shared_data:/shared_data
      # - galaxy-conda:/galaxy/tool_deps
    depends_on:
      galaxy-postgres:
        condition: service_healthy
    restart: unless-stopped

  galaxy-postgres:
    build:
      context: ./containers/galaxy
      dockerfile: Dockerfile.postgres
    image: galaxy-postgres
    container_name: galaxy-postgres
    env_file: ./.envs/.galaxy-postgres
    ports:
      - "5432:5432"
    volumes:
      - galaxy-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galaxy"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ===== APOLLO SERVICES =====
  apollo-server:
    build:
      context: ./containers/apollo
      dockerfile: Dockerfile.server
    container_name: apollo-server
    env_file: ./.envs/.apollo
    ports:
      - 3999:3999
    volumes:
      - ./uploads/apollo:/data/uploads
    depends_on:
      apollo-mongo:
        condition: service_healthy
    restart: unless-stopped

  apollo-client:
    build:
      context: ./containers/apollo
      dockerfile: Dockerfile.client
      args:
        JBROWSE_VERSION: 2.18.0
        APOLLO_VERSION: 0.3.1
    container_name: apollo-client
    ports:
      - '8888:80'
    volumes:
      - ./deployment/data/:/usr/local/apache2/htdocs/data/
      - ./deployment/demoData/:/usr/local/apache2/htdocs/demoData/
    depends_on:
      - apollo-server
    restart: unless-stopped

  apollo-mongo:
    build:
      context: ./containers/apollo
      dockerfile: Dockerfile.mongodb
    container_name: apollo-mongo
    command:
      - '--replSet'
      - 'rs0'
      - '--bind_ip_all'
      - '--port'
      - '27017'
    healthcheck:
      interval: 30s
      retries: 3
      start_interval: 5s
      start_period: 2m
      test: ["CMD", "/scripts/mongo_healthcheck.sh"]
      timeout: 10s
    volumes:
      - apollo-mongo-data:/data/db
      - apollo-mongo-config:/data/configdb
    ports:
      - '27017:27017'
    restart: unless-stopped

  apollo-mongo-replica:
    build:
      context: ./containers/apollo
      dockerfile: Dockerfile.mongodb
    container_name: apollo-mongo-replica
    command:
      - '--replSet'
      - 'rs0'
      - '--bind_ip_all'
      - '--port'
      - '27018'
    ports:
      - '27018:27018'
    volumes:
      - apollo-mongo-replica-data:/data/db
      - apollo-mongo-replica-config:/data/configdb
    restart: unless-stopped